### ISSUE TITLE
Error when running Yarn Test

### ISSUE THREAD

**Issue by Je12emy** [benawad/fullstack-graphql-airbnb-clone#37]
I've had this error recently when running `Yarn Test` and I was wondering if it could be related to my Postgress database or maybe my postgress user privileges, all other tests are passing.
```
 FAIL  src/modules/user/register/register.test.ts
  Register user
    ✕ check bad password (168ms)
    ✕ check bad password and bad email (8ms)
    ○ skipped check for duplicate emails
    ○ skipped check bad email

  ● Register user › check bad password

    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

      Object {
    -   "register": Array [
    -     Object {
    -       "message": "password must be at least 3 characters",
    -       "path": "password",
    -     },
    -   ],
    +   "register": null,
      }

      65 |     // catch bad password
      66 |     const response4 = await client.register(faker.internet.email(), "ad");
    > 67 |     expect(response4.data).toEqual({
         |                            ^
      68 |       register: [
      69 |         {
      70 |           path: "password",

      at Object.<anonymous> (src/modules/user/register/register.test.ts:67:28)
      at fulfilled (src/modules/user/register/register.test.ts:4:56)

  ● Register user › check bad password and bad email

    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

      Object {
        "register": Array [
          Object {
    -       "message": "email must be at least 2 characters",
    -       "path": "email",
    -     },
    -     Object {
            "message": "email must be a valid email",
            "path": "email",
    -     },
    -     Object {
    -       "message": "password must be at least 3 characters",
    -       "path": "password",
          },
        ],
      }

      77 |   it("check bad password and bad email", async () => {
      78 |     const response5 = await client.register("df", "ad");
    > 79 |     expect(response5.data).toEqual({
         |                            ^
      80 |       register: [
      81 |         {
      82 |           path: "email",

      at Object.<anonymous> (src/modules/user/register/register.test.ts:79:28)
      at fulfilled (src/modules/user/register/register.test.ts:4:56)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 skipped, 4 total
Snapshots:   0 total
Time:        1.85s, estimated 2s
Ran all test suites.

```

**Comment by benawad** [comment]
hard to say from the output, just says it returned null. Might be related to db user.

**Comment by Je12emy** [comment]
After some digging I realized I may have altered the Yup schema to allow a different minimum size, which did not trigger the **expected** error.
